name: Build containers


permissions:
  contents: read
  packages: write
  id-token: write

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 7 * * 1"  # Run once weekly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger-build:
    name: Build containers
    strategy:
      fail-fast: false
      matrix:
        cuda-version: [12_2, 12_9, 13_0, 13_1]
        arch: [x86_64, aarch64]
        manylinux-base: [manylinux_2_28, manylinux_2_34]
    runs-on: ${{ matrix.arch == 'x86_64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      - name: Log in to quay.io container registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}

      - name: Compute image tag
        id: compute-image-tag
        run: |
          COMMIT_SHA=${{ github.sha }}
          COMMIT_DATE=$(git show -s --format=%cd --date=short ${COMMIT_SHA})
          BUILD_NUMBER=$(git rev-list "--since=${COMMIT_DATE}T00:00:00Z" --first-parent --count ${COMMIT_SHA})
          IMAGE_TAG=${COMMIT_DATE//-/.}-${BUILD_NUMBER}
          IMAGE_REPO=quay.io/manylinux_cuda/${{ matrix.manylinux-base }}_${{ matrix.arch }}_cuda${{ matrix.cuda-version }}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> "$GITHUB_OUTPUT"
          echo "IMAGE_REPO=${IMAGE_REPO}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f
        with:
          file: Dockerfile
          push: true
          tags: |
            ${{ steps.compute-image-tag.outputs.IMAGE_REPO }}:latest
            ${{ steps.compute-image-tag.outputs.IMAGE_REPO }}:${{ steps.compute-image-tag.outputs.IMAGE_TAG }}
          build-args: |
            CUDA_VERSION=${{ matrix.cuda-version }}
            NCCL_VERSION=${{ matrix.nccl-version }}
            MANYLINUX_BASE=${{ matrix.manylinux-base }}
            ARCH=${{ matrix.arch }}
