name: Example GPU CI/CD

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  build-wheel:
    name: Build wheel
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gpu-ci-demo/example_gpu_ci:cuda_build
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6.0.2
      - run: python -m build -v --wheel
